"""empty message

Revision ID: ba41530d1320
Revises: 
Create Date: 2020-02-07 22:55:58.355557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba41530d1320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('graduate_date', sa.DateTime(), nullable=False),
    sa.Column('education_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('skill_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fathername', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=100000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('project_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('work', sa.String(length=512), nullable=True),
    sa.Column('entery_date', sa.DateTime(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=False),
    sa.Column('experience_description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('skill')
    op.drop_table('language')
    op.drop_table('education')
    # ### end Alembic commands ###
